import Header from '@/app/ui/header'
import Sidebar from '@/app/ui/sidebar'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <head>
        <link
          href="https://use.fontawesome.com/releases/v5.15.3/css/all.css"
          rel="stylesheet"
        ></link>
      </head>
      <body className={inter.className}>
        <Header />
        <div className="clear-right"></div>
        <div className="main-wrapper">
          <Sidebar />
          <div className="content-wrapper">{children}</div>
        </div>
      </body>
    </html>
  )
}
